config/routes.rb
Ana::Application.routes.draw do
  get "check/anagram"
  post "check/anagram"

  root 'check#anagram'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/check_controller.rb
class CheckController < ApplicationController
  def anagram
  	@w1=params[:firstword]
  	@w2=params[:secondword]
  	@foo=nil
    @wd1=@w1.to_s.delete('^a-zA-Z `~!@#$%^&*()-=+{}\|/.,<>;:\'?')
    @wd2=@w2.to_s.delete('^a-zA-Z `~!@#$%^&*()-=+{}\|/.,<>;:\'?')
    @w1=@w1.to_s.delete('^a-zA-Z')
    @w2=@w2.to_s.delete('^a-zA-Z')
  	if(@wd1.to_s.length>0 && @wd2.to_s.length>0)
  		@foo=checkanagram(@w1,@w2)
  	end
  end
  private
 	def checkanagram(word1,word2)
    	word1 = word1.to_s.downcase.split('').sort
    	word2 = word2.to_s.downcase.split('').sort
      if(word1.length>0 && word2.length>0)
    	   word1 == word2 ? true : false
      else
        false
      end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_helper.rb
module CheckHelper
end

app/views/check/anagram.html.erb
<div class="container">
	<div class="inner">

	</div>
	
</div>
<div class="workarea" id="anagrams">
		<%=form_tag check_anagram_path do %>
		<%= text_field :firstword,'', :placeholder=>"First Word", :class=>"tbox", :required=>"required"%>
		<%= text_field :secondword,'', :placeholder=>"Second Word", :class=>"tbox", :required=>"required"%>
		<%= submit_tag "Submit", :class=>"tbox button"%>
		<% end %>
		
</div>
<div class="workarea" id="found">

		<div><h1 class="tbox rt_text st" style="text-align: center">You found ANAGRAMS!!</h1>
			<%= text_field :firstword,'', :value=>@wd1, :class=>"tbox rt_text st", :required=>"required", :disabled=>"disabled"%>
		<%= text_field :secondword,'', :value=>@wd2, :class=>"tbox rt_text st", :required=>"required", :disabled=>"disabled"%>
			<input type="button" value="Check New Words" onclick="toggle_visibility()" class="tbox right st"/>
		</div>
</div>
<div class="workarea" id="notfound">
		
		<div><h1 class="tbox wr_text">Looks like the words you entered are not Anagrams!</h1>
			<input type="button" value="Try Again" onclick="toggle_visibility()" class="tbox wrong"/>
		</div>
	</div>

<%= javascript_tag do %>
	var result= "<%= @foo %>";
	console.log(result);
	var v='';
	var u=document.getElementById('anagrams');
	if(result=="true")
	{
		console.log("going true");

		v=document.getElementById('found');
		toggle_visibility();
	}
	else if (result=="false") 
		{
		console.log("going false");

		v=document.getElementById('notfound');
			toggle_visibility();
		}
	function toggle_visibility() {
     if(v.style.display == "block")
     {
     	console.log("in sign off");
     	u.style.display="block";
         v.style.display = 'none';
     }
      else
      {
      	console.log("in sigin in");
     	u.style.display='none';
         v.style.display = 'block';
     }
 }
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
<head>
  <title>Anagrams</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
 
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="head">
	ANAGRAM
</div>
<div class="blur">
</div>

<%= yield %>

</body>
</html>